In [5]:
# Import dependencies
import pandas as pd
import psycopg2

import sqlalchemy
from sqlalchemy import create_engine

In [10]:
# Create an engine instance
alchemyEngine = create_engine('postgresql+psycopg2://root:Group2Wineos@grp2rdsinstance.cwkbfcctxu7y.us-east-1.rds.amazonaws.com/postgres')

In [11]:
# Connect to PostgreSQL server
dbConnection = alchemyEngine.connect();

In [12]:
df = pd.read_sql_table('wine_weather_table', dbConnection)
df

,province,year,variety,points,prov_weather,year_weather,precipitation,temperature,timeseries
0,Sicilia,2013,White Blend,87,Sicilia,2013,368.81,18.53,Projected
1,Sicilia,2013,White Blend,87,Sicilia,2013,476.10,17.50,Historical
2,Oregon,2013,Pinot Gris,87,Oregon,2013,1094.03,9.07,Projected
3,Oregon,2013,Pinot Gris,87,Oregon,2013,440.10,8.68,Historical
4,Oregon,2012,Pinot Noir,87,Oregon,2012,1027.31,9.38,Projected
...,...,...,...,...,...,...,...,...,...
150063,Alsace,2013,Gewürztraminer,90,Alsace,2013,949.40,9.94,Historical
150064,Alsace,2012,Pinot Gris,90,Alsace,2012,1255.77,9.40,Projected
150065,Alsace,2012,Pinot Gris,90,Alsace,2012,938.63,10.39,Historical
150066,Alsace,2012,Gewürztraminer,90,Alsace,2012,1255.77,9.40,Projected
150067,Alsace,2012,Gewürztraminer,90,Alsace,2012,938.63,10.39,Historical